// The drop has to put people somewhere they can walk out of (POK-251).
//
// `tools/br/landing-reach.ts` marks the cells it cannot, and app.ts filters those
// before the Director or the bots see the pool. This is the check that the marks in
// the committed landing.json are still right for the committed world.json -- the two
// are generated by different tools and nothing else would notice them drifting apart.
import { describe, expect, it } from 'vitest';
import { World, type Spot, type WorldMap } from './world';
import worldData from '../data/world.json';
import { LANDING, LANDING_ALL } from '../match/landing';

const maps = (worldData as { maps: WorldMap[] }).maps;
const world = new World(maps);
const cells = LANDING_ALL;
const live = LANDING;

/** Everything reachable from one cell ON FOOT -- the same walk `landing-reach.ts`
 *  does. Surfing is deliberately not allowed: SURF needs a water mon that a trainer
 *  may never be dealt, so a drop cell that requires it is a drop cell that strands
 *  somebody (Route 108, the Abandoned Ship's island, was the case that proved it). */
function component(from: Spot): Set<string> {
  const key = (s: Spot) => `${s.map}:${s.x},${s.y}`;
  const seen = new Set([key(from)]);
  const queue = [from];
  while (queue.length > 0) {
    const at = queue.pop()!;
    for (const { to } of world.neighbours(at, false)) {
      if (seen.has(key(to))) continue;
      seen.add(key(to));
      queue.push(to);
    }
  }
  return seen;
}

const reach = component({ map: live[0].map, x: live[0].x, y: live[0].y });

describe('the drop pool', () => {
  it('is every bit one connected piece of Hoenn', () => {
    const stranded = live.filter((c) => !reach.has(`${c.map}:${c.x},${c.y}`));
    expect(stranded.slice(0, 5)).toEqual([]);
  });

  it('is still big enough to run a match out of', () => {
    // 32 seats is the room cap; the Director deals one cell each and wants choice.
    expect(live.length).toBeGreaterThan(500);
    expect(new Set(live.map((c) => maps.find((m) => m.id === c.map)?.section)).size).toBeGreaterThan(20);
  });

  it('marks off only cells that really are cut off', () => {
    // The other direction: nothing should be marked off that the flood can reach, or
    // the pool is being trimmed for no reason.
    const wrongly = cells.filter((c) => c.off && reach.has(`${c.map}:${c.x},${c.y}`));
    expect(wrongly.slice(0, 5)).toEqual([]);
  });
});
