// The drop has to put people somewhere they can walk out of (POK-251).
//
// `tools/br/landing-reach.ts` marks the cells it cannot, and app.ts filters those
// before the Director or the bots see the pool. This is the check that the marks in
// the committed landing.json are still right for the committed world.json -- the two
// are generated by different tools and nothing else would notice them drifting apart.
import { describe, expect, it } from 'vitest';
import { World, type Spot, type WorldMap } from './world';
import worldData from '../data/world.json';
import { DOORSTEPS, LANDING, LANDING_ALL } from '../match/landing';

const maps = (worldData as { maps: WorldMap[] }).maps;
const world = new World(maps);
const cells = LANDING_ALL;
const live = LANDING;

/** Everything reachable from one cell ON FOOT -- the same walk `landing-reach.ts`
 *  does. Surfing is deliberately not allowed: SURF needs a water mon that a trainer
 *  may never be dealt, so a drop cell that requires it is a drop cell that strands
 *  somebody (Route 108, the Abandoned Ship's island, was the case that proved it). */
/** A place: a cell, or one level of a bridge (POK-331 #2), which is somewhere of its own. */
const key = (s: Spot) => (s.z === undefined ? `${s.map}:${s.x},${s.y}` : `${s.map}:${s.x},${s.y}@${s.z}`);

function component(from: Spot): Set<string> {
  const seen = new Set([key(from)]);
  const queue = [from];
  while (queue.length > 0) {
    const at = queue.pop()!;
    // On foot, but able to cut: every contestant boots with the HMs (POK-256), which
    // is the same assumption tools/br/landing-reach.ts floods the world with.
    for (const { to } of world.neighbours(at, false, true)) {
      if (seen.has(key(to))) continue;
      seen.add(key(to));
      queue.push(to);
    }
  }
  return seen;
}

const reach = component({ map: live[0].map, x: live[0].x, y: live[0].y });

/** Is a drop here in the rest of the pool? On a bridge, a trainer is dropped at no level
 *  (pret spawns them at height 0, off at either), which is a place nothing else walks
 *  onto: they are in if either level is. landing-reach.ts judges it the same way. */
function joined(c: Spot): boolean {
  return [c, ...world.levels(c.map, c.x, c.y).map((z) => ({ ...c, z }))].some((s) => reach.has(key(s)));
}

describe('the drop pool', () => {
  it('is every bit one connected piece of Hoenn', () => {
    const stranded = live.filter((c) => !joined({ map: c.map, x: c.x, y: c.y }));
    expect(stranded.slice(0, 5)).toEqual([]);
  });

  it('is still big enough to run a match out of', () => {
    // 32 seats is the room cap; the Director deals one cell each and wants choice.
    expect(live.length).toBeGreaterThan(500);
    expect(new Set(live.map((c) => maps.find((m) => m.id === c.map)?.section)).size).toBeGreaterThan(20);
  });

  it('marks off only cells that really are cut off', () => {
    // The other direction: nothing should be marked off that the flood can reach, or
    // the pool is being trimmed for no reason.
    const wrongly = cells.filter((c) => c.off && joined({ map: c.map, x: c.x, y: c.y }));
    expect(wrongly.slice(0, 5)).toEqual([]);
  });
});


// POK-307. Cam picked Fortree City from the drop and landed on Route 117, behind the Day
// Care's fence, because Fortree had no droppable cell and the fallback was anywhere in
// Hoenn. Seven of Hoenn's towns are in that state -- the flood above walks, and most of
// eastern Hoenn is across water -- so this is the invariant that says a town the picker
// offers always has somewhere to put you.
describe('every town you can pick has somewhere to land (POK-307)', () => {
  /** A section is a town you can pick if one of its maps has a POKeMON CENTER on it.
   *  That is what MAPSECTYPE_CITY_CANFLY means in practice, and unlike the ROM's own
   *  type table it is in world.json where this test can read it. */
  const townSections = new Set(
    maps.filter((m) => m.outdoor && (m.warps ?? []).some((w) => w.kind === 'centre')).map((m) => m.section),
  );
  const sectionOf = new Map(maps.map((m) => [m.id, m.section]));
  const withCells = new Set([...live, ...DOORSTEPS].map((c) => sectionOf.get(c.map)));

  it('finds the towns at all', () => {
    // Hoenn has sixteen of them; a number far off that means world.json changed shape.
    expect(townSections.size).toBeGreaterThanOrEqual(12);
  });

  it('leaves none of them with nothing', () => {
    // The Battle Frontier is the one deliberate exception: the match does not go there
    // (POK-304 shut the ferry, and it is an island you cannot walk off), so it has no
    // cells and no doorsteps on purpose and a pick there lands in Hoenn instead.
    const empty = [...townSections].filter((s) => !withCells.has(s) && s !== 'MAPSEC_BATTLE_FRONTIER');
    expect(empty).toEqual([]);
  });

  it('has doorsteps ranked, nicest first', () => {
    const ranks = DOORSTEPS.map((c) => c.door ?? 9);
    expect(ranks).toEqual([...ranks].sort((a, b) => a - b));
    // A CENTRE is rank 0 and there is one in every town, so the list starts with them.
    expect(ranks[0]).toBe(0);
  });

  it('keeps doorsteps out of the ordinary pool', () => {
    expect(live.some((c) => c.door !== undefined)).toBe(false);
  });

  it('puts every doorstep somewhere standable', () => {
    for (const c of DOORSTEPS) expect(world.standable(c.map, c.x, c.y)).toBe(true);
  });
});
