#ifndef GUARD_BR_ROM_LIMITS_H
#define GUARD_BR_ROM_LIMITS_H

// Generated by tools/br/rom-limits.py from data/maps/map_groups.json -- do not edit by
// hand. web/src/net/rom-limits.test.ts fails when this drifts; re-run the script.
//
// How many maps each MAP_GROUP has, in group order: BrWire_MapOk's bound (POK-330 #43).
// A map past its group's count warps through gMapGroups into whatever follows it, and
// nothing in C says how many a group has. br_wire.c asserts the count is
// MAP_GROUPS_COUNT.
#define BR_MAP_GROUP_SIZES { 57, 5, 5, 6, 7, 8, 9, 7, 7, 14, 8, 17, 10, 23, 13, 15, 15, 2, 2, 2, 3, 1, 1, 1, 108, 61, 89, 2, 1, 13, 1, 1, 3, 1 }

#endif // GUARD_BR_ROM_LIMITS_H
