#ifndef GUARD_BR_WIRE_IDS_H
#define GUARD_BR_WIRE_IDS_H

// Generated by tools/br/wire-ids.py from tools/br/wire-table.txt -- do not edit by hand.
// web/src/net/wire-ids.test.ts fails when this drifts from the table; re-run the script.
// Each message's bytes are in br_wire.h, under its name.

// Message types on the mailbox rings.
#define BR_MSG_NONE 0
#define BR_MSG_ECHO 1
#define BR_MSG_PLACE 2
#define BR_MSG_STEP 3
#define BR_MSG_FACE 4
#define BR_MSG_CHALLENGE 5
#define BR_MSG_BT 6
#define BR_MSG_PARTY 7
#define BR_MSG_FAINT 8
#define BR_MSG_OUT 9
#define BR_MSG_PICKUP 10
#define BR_MSG_SPILL 11
#define BR_MSG_RING 12
#define BR_MSG_CLOCK 13
#define BR_MSG_START 14
#define BR_MSG_TICKER 15
#define BR_MSG_RESULT 16
#define BR_MSG_BUSY 17
#define BR_MSG_BSTART 18
#define BR_MSG_TURN 19
#define BR_MSG_FOLLOW 20
#define BR_MSG_PEEK 21
#define BR_MSG_SHOT 22
#define BR_MSG_TRAINER 23
#define BR_MSG_PICK 24
#define BR_MSG_LAND 25
#define BR_MSG_SPENT 26
#define BR_MSG_DUEL 27
#define BR_MSG_DRESULT 28
#define BR_MSG_FLED 29
#define BR_MSG_GIVE 30
#define BR_MSG_NPCOUT 31

// The highest type in use: br_mailbox.c keeps it below BR_MSG_COUNT.
#define BR_MSG_LAST BR_MSG_NPCOUT

// The most bytes each message that spans slots packs to, and so what the ROM's assembler
// for it has to hold (br_wire.h says why).
#define BR_CAP_BT 261         // seat, seq u16, len u16, a 256-byte block
#define BR_CAP_PARTY 667      // seat, count, 6 * 100, then money u32, stacks, 20 * (id, n)
#define BR_CAP_SPILL 128      // 4 + 6 * 9, bag flag, key/x/y, 8 * 3 items, money, 1 + 7 name
#define BR_CAP_START 266      // 10 + 32 spawn rows * 8
#define BR_CAP_BSTART 1230    // 28 + 2 * (count + 6 * 100): what a fighter's ROM sends
#define BR_CAP_TURN 128       // what a fighter's ROM sends in one frame
#define BR_CAP_TRAINER 619    // seat, 1 + 7 name, count, 6 * 100, items, 4 * u16
#define BR_CAP_DUEL 1222      // 4 + 12 * 100, then two bags of (count, 4 * u16)

// The table's shape, and the protocol tools/br/wire-protocols.txt lists it under (its
// last row). br_wire.c will not build unless that protocol is BR_PROTOCOL.
#define BR_WIRE_HASH 0x777CC3AA
#define BR_WIRE_PROTOCOL 1

#endif // GUARD_BR_WIRE_IDS_H
