// Generated by tools/br/rom-limits.py from the pret sources -- do not edit by hand.
// web/src/net/rom-limits.test.ts fails when this drifts from them; re-run the script.
//
// The ids a wire row may carry into a ROM (POK-330 #43): a species at or past
// NUM_SPECIES indexes gSpeciesNames and the pic tables out of bounds, a move at or past
// MOVES_COUNT indexes gBattleMoves, and a map past its group's count warps through
// gMapGroups into whatever follows it. wire.ts's decoders refuse all three.

/** include/constants/species.h: SPECIES_EGG, the first id past the real ones. */
export const NUM_SPECIES = 412;
/** SPECIES_OLD_UNOWN_B..Z: the "?" placeholders between CELEBI and TREECKO. */
export const SPECIES_UNOWN_GAP: readonly [number, number] = [252, 276];
/** include/constants/moves.h */
export const MOVES_COUNT = 355;
/** include/constants/pokemon.h */
export const MAX_LEVEL = 100;
/** data/maps/map_groups.json: how many maps each MAP_GROUP has, in group order. */
export const MAP_GROUP_SIZES: readonly number[] = [57, 5, 5, 6, 7, 8, 9, 7, 7, 14, 8, 17, 10, 23, 13, 15, 15, 2, 2, 2, 3, 1, 1, 1, 108, 61, 89, 2, 1, 13, 1, 1, 3, 1];
