import { describe, expect, it } from 'vitest';
import speciesHeader from '../../../include/constants/species.h?raw';
import movesHeader from '../../../include/constants/moves.h?raw';
import pokemonHeader from '../../../include/constants/pokemon.h?raw';
import mapGroupsJson from '../../../data/maps/map_groups.json?raw';
import romLimitsHeader from '../../../include/br/br_rom_limits.h?raw';
import { MAP_GROUP_SIZES, MAX_LEVEL, MOVES_COUNT, NUM_SPECIES, SPECIES_UNOWN_GAP } from './rom-limits';
import { WireError, decode } from './wire';

// rom-limits.ts and br_rom_limits.h are generated by tools/br/rom-limits.py, and these
// re-read the pret sources they came from: a pret merge that adds a species, a move or a
// map fails here until the script is run again (POK-330 #43).

const define = (text: string, name: string): number => {
  const m = new RegExp(`^#define ${name}\\s+(\\S+)`, 'm').exec(text);
  if (!m) throw new Error(`no ${name}`);
  return /^\d+$/.test(m[1]) ? Number(m[1]) : define(text, m[1]);
};

describe('rom-limits.ts matches the pret sources', () => {
  it('species, moves and levels', () => {
    expect(NUM_SPECIES).toBe(define(speciesHeader, 'NUM_SPECIES'));
    expect(SPECIES_UNOWN_GAP).toEqual([
      define(speciesHeader, 'SPECIES_OLD_UNOWN_B'),
      define(speciesHeader, 'SPECIES_OLD_UNOWN_Z'),
    ]);
    expect(MOVES_COUNT).toBe(define(movesHeader, 'MOVES_COUNT'));
    expect(MAX_LEVEL).toBe(define(pokemonHeader, 'MAX_LEVEL'));
  });

  it('how many maps each group has, in both generated files', () => {
    const groups = JSON.parse(mapGroupsJson) as Record<string, string[]> & { group_order: string[] };
    const sizes = groups.group_order.map((g) => groups[g].length);
    expect(MAP_GROUP_SIZES).toEqual(sizes);
    const c = /#define BR_MAP_GROUP_SIZES \{([^}]*)\}/.exec(romLimitsHeader)![1];
    expect(c.split(',').map((n) => Number(n.trim()))).toEqual(sizes);
  });
});

describe('the decoders refuse ids no ROM has', () => {
  const mon = (species: number, move = 1) => ({
    species, level: 5, hp: 20, maxHp: 20, status: 0, moves: [{ id: move, pp: 35, ppUps: 0 }],
  });
  const trainer = (species: number, move = 1) =>
    JSON.stringify({ t: 'trainer', seat: 31, name: 'BOT', mons: [mon(species, move)] });
  const spill = (species: number, map = { group: 0, num: 9 }) =>
    JSON.stringify({ t: 'spill', seat: 3, map, mons: [{ key: 0x300, x: 10, y: 10, species, level: 30 }] });
  const land = (group: number, num: number) => JSON.stringify({ t: 'land', seat: 3, map: { group, num }, x: 10, y: 10 });

  it('takes the last real species, move and map of each group', () => {
    expect(() => decode(trainer(NUM_SPECIES - 1, MOVES_COUNT - 1))).not.toThrow();
    expect(() => decode(spill(251))).not.toThrow(); // CELEBI
    expect(() => decode(spill(277))).not.toThrow(); // TREECKO
    MAP_GROUP_SIZES.forEach((n, group) => expect(() => decode(land(group, n - 1))).not.toThrow());
  });

  it('refuses a species past the table, or a "?" placeholder', () => {
    for (const s of [NUM_SPECIES, 0xffff, SPECIES_UNOWN_GAP[0], 260, SPECIES_UNOWN_GAP[1]]) {
      expect(() => decode(spill(s))).toThrow(WireError);
      expect(() => decode(trainer(s))).toThrow(WireError);
    }
  });

  it('refuses a move past gBattleMoves', () => {
    expect(() => decode(trainer(277, MOVES_COUNT))).toThrow(WireError);
    expect(() => decode(trainer(277, 0xffff))).toThrow(WireError);
  });

  it('refuses a map past its group, or a group past gMapGroups', () => {
    expect(() => decode(land(MAP_GROUP_SIZES.length, 0))).toThrow(WireError);
    expect(() => decode(land(255, 0))).toThrow(WireError);
    expect(() => decode(land(0, MAP_GROUP_SIZES[0]))).toThrow(WireError);
    expect(() => decode(spill(277, { group: 33, num: 1 }))).toThrow(WireError);
  });
});
