// Generated by tools/br/wire-ids.py from tools/br/wire-table.txt -- do not edit by hand.
// web/src/net/wire-ids.test.ts fails when this drifts from the table; re-run the script.

/** The mailbox's message types: include/br/br_wire_ids.h's BR_MSG_*. Each one's bytes are
 *  in include/br/br_wire.h, under its name. */
export const BR_MSG = {
  NONE: 0,
  ECHO: 1,
  PLACE: 2,
  STEP: 3,
  FACE: 4,
  CHALLENGE: 5,
  BT: 6,
  PARTY: 7,
  FAINT: 8,
  OUT: 9,
  PICKUP: 10,
  SPILL: 11,
  RING: 12,
  CLOCK: 13,
  START: 14,
  TICKER: 15,
  RESULT: 16,
  BUSY: 17,
  BSTART: 18,
  TURN: 19,
  FOLLOW: 20,
  PEEK: 21,
  SHOT: 22,
  TRAINER: 23,
  PICK: 24,
  LAND: 25,
  SPENT: 26,
  DUEL: 27,
  DRESULT: 28,
  FLED: 29,
  GIVE: 30,
  NPCOUT: 31,
} as const;

/** The most bytes each message that spans slots packs to, and so what the ROM's
 *  assembler for it holds (BR_CAP_*): BrWire_Assemble drops a longer one without a word. */
export const BR_CAP = {
  BT: 261,          // seat, seq u16, len u16, a 256-byte block
  PARTY: 667,       // seat, count, 6 * 100, then money u32, stacks, 20 * (id, n)
  SPILL: 128,       // 4 + 6 * 9, bag flag, key/x/y, 8 * 3 items, money, 1 + 7 name
  START: 266,       // 10 + 32 spawn rows * 8
  BSTART: 1230,     // 28 + 2 * (count + 6 * 100): what a fighter's ROM sends
  TURN: 128,        // what a fighter's ROM sends in one frame
  TRAINER: 619,     // seat, 1 + 7 name, count, 6 * 100, items, 4 * u16
  DUEL: 1222,       // 4 + 12 * 100, then two bags of (count, 4 * u16)
} as const;

/** The table's shape (BR_WIRE_HASH), which include/br/br_version.h pins next to
 *  BR_PROTOCOL. */
export const WIRE_HASH = 0x777CC3AA;
