#!/usr/bin/env python3
"""Generate the id bounds the page and the ROM check wire rows against (POK-330 #43).

    python3 tools/br/rom-limits.py

Writes two files, both checked in:

  web/src/net/rom-limits.ts    NUM_SPECIES, the "?" block, MOVES_COUNT, MAX_LEVEL and
                               how many maps each group has -- what wire.ts's decoders
                               bound species, move and map ids by.
  include/br/br_rom_limits.h   the per-group map counts, for BrWire_MapOk. The ROM has
                               NUM_SPECIES and the rest as constants already; how many
                               maps a group has is nowhere in C.

Read out of the pret sources: include/constants/species.h, moves.h and pokemon.h, and
data/maps/map_groups.json (not the generated map_groups.h, which only exists after a
build). web/src/net/rom-limits.test.ts reads the same sources and fails when either file
has drifted from them -- re-run this after a pret merge that adds a species, a move or
a map.
"""
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


def define(text, name):
    m = re.search(r"^#define %s\s+(\S+)" % name, text, re.M)
    if not m:
        sys.exit("no %s" % name)
    return m.group(1)


def number(text, name):
    v = define(text, name)
    return int(v, 0) if re.match(r"^(0x[0-9a-fA-F]+|\d+)$", v) else number(text, v)


def main():
    species = read("include/constants/species.h")
    moves = read("include/constants/moves.h")
    pokemon = read("include/constants/pokemon.h")
    groups = json.loads(read("data/maps/map_groups.json"))

    num_species = number(species, "NUM_SPECIES")
    unown_first = number(species, "SPECIES_OLD_UNOWN_B")
    unown_last = number(species, "SPECIES_OLD_UNOWN_Z")
    moves_count = number(moves, "MOVES_COUNT")
    max_level = number(pokemon, "MAX_LEVEL")
    sizes = [len(groups[g]) for g in groups["group_order"]]

    ts = f"""// Generated by tools/br/rom-limits.py from the pret sources -- do not edit by hand.
// web/src/net/rom-limits.test.ts fails when this drifts from them; re-run the script.
//
// The ids a wire row may carry into a ROM (POK-330 #43): a species at or past
// NUM_SPECIES indexes gSpeciesNames and the pic tables out of bounds, a move at or past
// MOVES_COUNT indexes gBattleMoves, and a map past its group's count warps through
// gMapGroups into whatever follows it. wire.ts's decoders refuse all three.

/** include/constants/species.h: SPECIES_EGG, the first id past the real ones. */
export const NUM_SPECIES = {num_species};
/** SPECIES_OLD_UNOWN_B..Z: the "?" placeholders between CELEBI and TREECKO. */
export const SPECIES_UNOWN_GAP: readonly [number, number] = [{unown_first}, {unown_last}];
/** include/constants/moves.h */
export const MOVES_COUNT = {moves_count};
/** include/constants/pokemon.h */
export const MAX_LEVEL = {max_level};
/** data/maps/map_groups.json: how many maps each MAP_GROUP has, in group order. */
export const MAP_GROUP_SIZES: readonly number[] = [{", ".join(str(n) for n in sizes)}];
"""
    h = f"""#ifndef GUARD_BR_ROM_LIMITS_H
#define GUARD_BR_ROM_LIMITS_H

// Generated by tools/br/rom-limits.py from data/maps/map_groups.json -- do not edit by
// hand. web/src/net/rom-limits.test.ts fails when this drifts; re-run the script.
//
// How many maps each MAP_GROUP has, in group order: BrWire_MapOk's bound (POK-330 #43).
// A map past its group's count warps through gMapGroups into whatever follows it, and
// nothing in C says how many a group has. br_wire.c asserts the count is
// MAP_GROUPS_COUNT.
#define BR_MAP_GROUP_SIZES {{ {", ".join(str(n) for n in sizes)} }}

#endif // GUARD_BR_ROM_LIMITS_H
"""
    for rel, text in (("web/src/net/rom-limits.ts", ts), ("include/br/br_rom_limits.h", h)):
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote " + rel)


if __name__ == "__main__":
    main()
