#!/usr/bin/env python3
"""Generate the mailbox's message ids and reassembly caps from one table (POK-331 #21).

    python3 tools/br/wire-ids.py

Reads tools/br/wire-table.txt and writes two files, both checked in:

  include/br/br_wire_ids.h   BR_MSG_* and BR_MSG_LAST, BR_CAP_*, and BR_WIRE_HASH -- what
                             br_wire.h includes, so the ROM and its handlers see the same
                             numbers they always did.
  web/src/net/wire-ids.ts    BR_MSG, BR_CAP and WIRE_HASH, for slots.ts and the tests.

The two sides of the mailbox used to carry the ids by hand, tied together by a comment.
web/src/net/wire-ids.test.ts reads the table and fails when either file has drifted from
it; re-run this after editing the table.

BR_WIRE_HASH is FNV-1a (32-bit) over the rows sorted by id, one `NAME ID` or `NAME ID CAP`
line each, joined by newlines -- the notes are not in it. The table's shape is part of
the protocol: tools/br/wire-protocols.txt lists every table's hash under the protocol it
went out in, append-only, and this writes nothing while the table's hash is not its last
row's. The last row's protocol goes into br_wire_ids.h as BR_WIRE_PROTOCOL, which
br_wire.c STATIC_ASSERTs is BR_PROTOCOL.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TABLE = "tools/br/wire-table.txt"
PROTOCOLS = "tools/br/wire-protocols.txt"
CONT = 0x80

ROW = re.compile(r"^([A-Z][A-Z0-9_]*)\s+(\d+)(?:\s+(\d+))?\s*(?:#\s*(.*?))?\s*$")


def rows():
    """[(name, id, cap or None, note)], in the table's order."""
    out = []
    with open(os.path.join(ROOT, TABLE), encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip("\r\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            m = ROW.match(line)
            if not m:
                sys.exit("%s:%d: not NAME ID [CAP] [# note]: %s" % (TABLE, n, line))
            name, ident, cap, note = m.group(1), int(m.group(2)), m.group(3), m.group(4)
            out.append((name, ident, int(cap) if cap else None, note or ""))
    names = [r[0] for r in out]
    ids = [r[1] for r in out]
    for name in set(names):
        if names.count(name) > 1:
            sys.exit("%s: %s is in the table twice" % (TABLE, name))
    for ident in set(ids):
        if ids.count(ident) > 1:
            sys.exit("%s: two messages are %d" % (TABLE, ident))
        if ident >= CONT:
            sys.exit("%s: %d sets the continuation bit 0x80" % (TABLE, ident))
    return out


def protocols():
    """[(protocol, hash)] from wire-protocols.txt, oldest first."""
    out = []
    with open(os.path.join(ROOT, PROTOCOLS), encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = re.match(r"^(\d+)\s+0x([0-9A-F]{8})$", line)
            if not m:
                sys.exit("%s:%d: not PROTOCOL 0xHASH: %s" % (PROTOCOLS, n, line))
            out.append((int(m.group(1)), int(m.group(2), 16)))
    if not out:
        sys.exit("%s: no rows" % PROTOCOLS)
    for a, b in zip(out, out[1:]):
        if b[0] <= a[0]:
            sys.exit("%s: protocol %d comes after %d; rows go oldest first" % (PROTOCOLS, b[0], a[0]))
    return out


def canonical(table):
    lines = []
    for name, ident, cap, _ in sorted(table, key=lambda r: r[1]):
        lines.append("%s %d" % (name, ident) if cap is None else "%s %d %d" % (name, ident, cap))
    return "\n".join(lines)


def fnv1a(text):
    h = 0x811C9DC5
    for b in text.encode("ascii"):
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def main():
    table = rows()
    by_id = sorted(table, key=lambda r: r[1])
    capped = [r for r in by_id if r[2] is not None]
    last = by_id[-1][0]
    digest = "0x%08X" % fnv1a(canonical(table))
    width = max(len(r[0]) for r in table)
    rows_p = protocols()
    protocol, pinned = rows_p[-1]
    if "0x%08X" % pinned != digest:
        sys.exit(
            "%s is %s, and the last row of %s is protocol %d at 0x%08X.\n"
            "The table changed shape, which is a new protocol: append the row\n"
            "    %d           %s\n"
            "to %s, bump BR_PROTOCOL in include/br/br_version.h and PROTOCOL in\n"
            "web/src/net/wire.ts to %d, and run this again. Never change a row that is\n"
            "already there." % (TABLE, digest, PROTOCOLS, protocol, pinned, protocol + 1, digest,
                                 PROTOCOLS, protocol + 1)
        )

    h_ids = "\n".join("#define BR_MSG_%s %d" % (r[0], r[1]) for r in by_id)
    h_caps = "\n".join(
        ("#define BR_CAP_%s %d" % (r[0], r[2])).ljust(len("#define BR_CAP_") + width + 6)
        + ("// " + r[3] if r[3] else "")
        for r in capped
    )
    h = f"""#ifndef GUARD_BR_WIRE_IDS_H
#define GUARD_BR_WIRE_IDS_H

// Generated by tools/br/wire-ids.py from {TABLE} -- do not edit by hand.
// web/src/net/wire-ids.test.ts fails when this drifts from the table; re-run the script.
// Each message's bytes are in br_wire.h, under its name.

// Message types on the mailbox rings.
{h_ids}

// The highest type in use: br_mailbox.c keeps it below BR_MSG_COUNT.
#define BR_MSG_LAST BR_MSG_{last}

// The most bytes each message that spans slots packs to, and so what the ROM's assembler
// for it has to hold (br_wire.h says why).
{h_caps}

// The table's shape, and the protocol tools/br/wire-protocols.txt lists it under (its
// last row). br_wire.c will not build unless that protocol is BR_PROTOCOL.
#define BR_WIRE_HASH {digest}
#define BR_WIRE_PROTOCOL {protocol}

#endif // GUARD_BR_WIRE_IDS_H
"""
    ts_ids = "\n".join("  %s: %d," % (r[0], r[1]) for r in by_id)
    ts_caps = "\n".join(
        ("  %s: %d," % (r[0], r[2])).ljust(width + 10) + (" // " + r[3] if r[3] else "") for r in capped
    )
    ts = f"""// Generated by tools/br/wire-ids.py from {TABLE} -- do not edit by hand.
// web/src/net/wire-ids.test.ts fails when this drifts from the table; re-run the script.

/** The mailbox's message types: include/br/br_wire_ids.h's BR_MSG_*. Each one's bytes are
 *  in include/br/br_wire.h, under its name. */
export const BR_MSG = {{
{ts_ids}
}} as const;

/** The most bytes each message that spans slots packs to, and so what the ROM's
 *  assembler for it holds (BR_CAP_*): BrWire_Assemble drops a longer one without a word. */
export const BR_CAP = {{
{ts_caps}
}} as const;

/** The table's shape (BR_WIRE_HASH), and the protocol tools/br/wire-protocols.txt lists
 *  it under (BR_WIRE_PROTOCOL): wire-ids.test.ts holds that to wire.ts's PROTOCOL. */
export const WIRE_HASH = {digest};
export const WIRE_PROTOCOL = {protocol};
"""
    for rel, text in (("include/br/br_wire_ids.h", h), ("web/src/net/wire-ids.ts", ts)):
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote " + rel)
    print("BR_WIRE_HASH %s, protocol %d" % (digest, protocol))


if __name__ == "__main__":
    main()
